services:
  mysql:
    image: mysql:8.0
    container_name: taskmanager_mysql
    restart: always
    environment:
      MYSQL_DATABASE: taskmanager
      MYSQL_ROOT_PASSWORD: "@miN1388"
      MYSQL_USER: amin
      MYSQL_PASSWORD: "@miN1388"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskmanager_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: amin
      DB_PASSWORD: "@miN1388"
      DB_NAME: taskmanager
      JWT_SECRET: "task-manager-secret-key-2024-amin"
      PORT: "8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - taskmanager_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager_frontend
    restart: always
    ports:
      - "3000:3000"  # تغییر از 3000:80 به 3000:3000
    environment:
      REACT_APP_API_URL: "http://localhost:8080/api"
    depends_on:
      - backend
    networks:
      - taskmanager_network

volumes:
  mysql_data:

networks:
  taskmanager_network:
    driver: bridge
